### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by Lewiscowles1986** [chozabu/Neinjarz#1]
So I got this working with Python3 on xenial (want to show my nephew what pygame can do)

Not sure if it is of interest to you, but [link](https://github.com/Lewiscowles1986/Neinjarz/tree/python3)

I think it's probably a good idea to keep 2 and 3 code separate.

**Comment by chozabu** [comment]
Fantastic! Sure is of interest to me - I only now realise it is 2 years
since I updated it to work with my setup at the time! and 5 years since I
put it on github (this was quite some time after developing it too)

I've been toying with the idea of updating this game for a while, tidying
up the networking, adding a menu, server list and/or matchmaking - not sure
I will get round to it too soon, but this is a darn good push in that
direction!

I'd like to have python2 and python3 on the same branch - but this is in no
way important, I nearly exclusivly use python3 these days.
I may mark my current master with a tag or branch and upgrade to your
python3 version

Going a bit off-topic, but you may be interested in pygame zero (
https://pygame-zero.readthedocs.io/en/latest/ ) - it's a somewhat
simplified pygame wrapper (to show to your nephew)
Also - not python related, but UnrealEngine4 has a interesting
turning-complete graphical language - blueprints (very heavy system to run
though)

-Alex "Chozabu http://chozabu.net/blog" P-B

**Comment by Lewiscowles1986** [comment]
That is a super cool response. Want me to make a PR?

**Comment by chozabu** [comment]
Sure thing :)

-Alex "Chozabu http://chozabu.net/blog" P-B
